# Generated by Django 3.0.3 on 2020-02-24 22:55

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('override_date_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorName', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'logo',
                'verbose_name_plural': 'logos',
            },
        ),
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('media_file', models.FileField(upload_to='')),
                ('media_type', models.CharField(choices=[('', 'Select Media Type'), ('img', 'IMAGE'), ('video', 'VIDEO')], max_length=15)),
            ],
            options={
                'verbose_name': 'media file',
                'verbose_name_plural': 'media files',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('roomID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location_name', models.TextField(blank=True, null=True)),
                ('override_date_time', models.DateTimeField(blank=True, null=True)),
                ('page_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('rotating_media_interval', models.PositiveSmallIntegerField(blank=True, default=15, null=True, validators=[django.core.validators.MaxValueValidator(400), django.core.validators.MinValueValidator(7)])),
                ('current_template', models.CharField(choices=[('today_standard', 'Default'), ('creatorcon', 'Creator Con'), ('noheader', 'Hide Header')], default='today_standard', max_length=255)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge2020.Event')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge2020.Logos')),
                ('related_rooms', models.ManyToManyField(blank=True, related_name='_rooms_related_rooms_+', to='knowledge2020.Rooms')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('agenda_session_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=32)),
                ('session_code', models.CharField(blank=True, max_length=32, null=True)),
                ('scheduleStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('session_type', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('ad_hoc_session', models.NullBooleanField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge2020.Rooms')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge2020.Logos')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('speaker_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('sessions', models.ManyToManyField(to='knowledge2020.Sessions')),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
            },
        ),
        migrations.CreateModel(
            name='ScheduledMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('list_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge2020.MediaFiles')),
                ('room', models.ManyToManyField(to='knowledge2020.Rooms')),
            ],
            options={
                'verbose_name': 'Scheduled Media',
                'verbose_name_plural': 'Scheduled Media',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('global_message', models.BooleanField(default=False)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge2020.Rooms')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.AddField(
            model_name='logos',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge2020.MediaFiles'),
        ),
    ]
