# Generated by Django 3.0.3 on 2020-02-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge2020', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='refreshKey',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
